spring:
  application:
    name: studyJava
  datasource:
    url: jdbc:mysql://localhost:3306/studyJava?useSSL=false&serverTimezone=UTC
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8888

#country:
#  name:jiangyd
#  system: socialism


