spring:
  application:
    name: studyJava
  datasource:
    url: jdbc:mysql://localhost:3306/studyJava?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # 设置传输大小
      max-file-size: 2048MB
      max-request-size: 2048MB
  redis:
    data:
      host: localhost
      port: 6379

server:
    port: 8888

token:
    key: studyJava2024

mybatis:
  mapper-locations: classpath:mapper/*.xml

minio:
  endpoint: https://119.91.213.59:9000
  apiIP: https://119.91.213.59:9001
  accessKey: ipNwUYoB7cz7ABHEOgCL
  secretKey: ZE6dOTog1TehM4poyCQQnZADUr0nr9ncIRxqGCV2
  bucketName: mhist




